Nem sempre ter muitos atributos significa melhores resultados, as vezes é melhor selecionar os melhores

In [1]:
import pandas as pd
base_census = pd.read_csv('/content/drive/MyDrive/Machine Learning e Data Science com Python de A a Z/Bases de dados/census.csv')
base_census.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [2]:
colunas = base_census.columns
colunas

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loos', 'hour-per-week', 'native-country',
       'income'],
      dtype='object')

In [3]:
X_census = base_census.iloc[:, 0:14].values
y_census = base_census.iloc[:, 14].values

In [4]:
# Criamops um labelEncoder para cada um dos atributos
from sklearn.preprocessing import LabelEncoder
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()
# aplicamos um labelEncoder para cada um dos atributos
X_census[:,1] = label_encoder_workclass.fit_transform(X_census[:,1])
X_census[:,3] = label_encoder_education.fit_transform(X_census[:,3])
X_census[:,5] = label_encoder_marital.fit_transform(X_census[:,5])
X_census[:,6] = label_encoder_occupation.fit_transform(X_census[:,6])
X_census[:,7] = label_encoder_relationship.fit_transform(X_census[:,7])
X_census[:,8] = label_encoder_race.fit_transform(X_census[:,8])
X_census[:,9] = label_encoder_sex.fit_transform(X_census[:,9])
X_census[:,13] = label_encoder_country.fit_transform(X_census[:,13])

In [5]:
X_census

array([[39, 7, 77516, ..., 0, 40, 39],
       [50, 6, 83311, ..., 0, 13, 39],
       [38, 4, 215646, ..., 0, 40, 39],
       ...,
       [58, 4, 151910, ..., 0, 40, 39],
       [22, 4, 201490, ..., 0, 20, 39],
       [52, 5, 287927, ..., 0, 40, 39]], dtype=object)

In [6]:
# Normalização dos dados
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_census_scaled = scaler.fit_transform(X_census)
X_census_scaled

array([[0.30136986, 0.875     , 0.0443019 , ..., 0.        , 0.39795918,
        0.95121951],
       [0.45205479, 0.75      , 0.0482376 , ..., 0.        , 0.12244898,
        0.95121951],
       [0.28767123, 0.5       , 0.13811345, ..., 0.        , 0.39795918,
        0.95121951],
       ...,
       [0.56164384, 0.5       , 0.09482688, ..., 0.        , 0.39795918,
        0.95121951],
       [0.06849315, 0.5       , 0.12849934, ..., 0.        , 0.19387755,
        0.95121951],
       [0.47945205, 0.625     , 0.18720338, ..., 0.        , 0.39795918,
        0.95121951]])

# Low Variance

Vão ser escolhidos os melhores atributos com base na variancia, buscando aqueles atributos que possuem uma variancia MAIOR, uma vez que geralmente aqueles que tem variancia muito baixa, sao parecidos, enquanto os maiores sao bastante diferentes, ajudando no treinamento do modelo

In [12]:
import numpy as np

In [9]:
X_census.shape[1] # Indica a quantidade de COLUNAS

14

In [11]:
for i in range(X_census.shape[1]): # iterar sobre o numero de colunas
  print(X_census_scaled[:, i].var()) # Vai mostrar a variancia de cada coluna

0.034913808595952486
0.03312115190663569
0.005138537590667898
0.06657103564450892
0.029416385024073417
0.06301761677301636
0.09123816653931152
0.10326534394406342
0.04502805169292987
0.22136950173699113
0.00545419549240862
0.008557270623428908
0.015874043397822807
0.03641266114220053


In [13]:
from sklearn.feature_selection import VarianceThreshold

In [15]:
selecao = VarianceThreshold(threshold=0.05) # Variancia minima
X_census_variancia = selecao.fit_transform(X_census_scaled)
X_census_variancia.shape

(32561, 5)

In [19]:
# PEgando os indices dos atributos selecionados
index = np.where(selecao.variances_ > 0.05)
index


(array([3, 5, 6, 7, 9]),)

In [20]:
colunas[index]

Index(['education', 'marital-status', 'occupation', 'relationship', 'sex'], dtype='object')

In [29]:
# Vendo se os resultados melhoraram
base_census_variancia = base_census.drop(columns = ['age', 'workclass', 'final-weight',
                                                    'education-num', 'race', 'capital-gain',
                                                    'capital-loos', 'hour-per-week',
                                                    'native-country'], axis = 1)
base_census_variancia

education       marital-status          occupation    relationship  \
0        Bachelors        Never-married        Adm-clerical   Not-in-family   
1        Bachelors   Married-civ-spouse     Exec-managerial         Husband   
2          HS-grad             Divorced   Handlers-cleaners   Not-in-family   
3             11th   Married-civ-spouse   Handlers-cleaners         Husband   
4        Bachelors   Married-civ-spouse      Prof-specialty            Wife   
...            ...                  ...                 ...             ...   
32556   Assoc-acdm   Married-civ-spouse        Tech-support            Wife   
32557      HS-grad   Married-civ-spouse   Machine-op-inspct         Husband   
32558      HS-grad              Widowed        Adm-clerical       Unmarried   
32559      HS-grad        Never-married        Adm-clerical       Own-child   
32560      HS-grad   Married-civ-spouse     Exec-managerial            Wife   

           sex  income  
0         Male   <=50K  
1         Male   <=50K  
2         Male   <=50K  
3         Male   <=50K  
4       Female   <=50K  
...        ...     ...  
32556   Female   <=50K  
32557     Male    >50K  
32558   Female   <=50K  
32559     Male   <=50K  
32560   Female    >50K  

[32561 rows x 6 columns]

Nova base de dados com as colunas aprovadas pelo low variance

In [30]:
X_census_variancia = base_census_variancia.iloc[:, 0:5].values
y_census_variancia = base_census_variancia.iloc[:, 5].values
X_census_variancia.shape, y_census_variancia.shape

((32561, 5), (32561,))

In [31]:
X_census_variancia


array([[' Bachelors', ' Never-married', ' Adm-clerical',
        ' Not-in-family', ' Male'],
       [' Bachelors', ' Married-civ-spouse', ' Exec-managerial',
        ' Husband', ' Male'],
       [' HS-grad', ' Divorced', ' Handlers-cleaners', ' Not-in-family',
        ' Male'],
       ...,
       [' HS-grad', ' Widowed', ' Adm-clerical', ' Unmarried', ' Female'],
       [' HS-grad', ' Never-married', ' Adm-clerical', ' Own-child',
        ' Male'],
       [' HS-grad', ' Married-civ-spouse', ' Exec-managerial', ' Wife',
        ' Female']], dtype=object)

In [32]:
X_census_variancia[:,0] = label_encoder_education.fit_transform(X_census_variancia[:,0])
X_census_variancia[:,1] = label_encoder_marital.fit_transform(X_census_variancia[:,1])
X_census_variancia[:,2] = label_encoder_occupation.fit_transform(X_census_variancia[:,2])
X_census_variancia[:,3] = label_encoder_relationship.fit_transform(X_census_variancia[:,3])
X_census_variancia[:,4] = label_encoder_sex.fit_transform(X_census_variancia[:,4])

In [33]:
X_census_variancia

array([[9, 4, 1, 1, 1],
       [9, 2, 4, 0, 1],
       [11, 0, 6, 1, 1],
       ...,
       [11, 6, 1, 4, 0],
       [11, 4, 1, 3, 1],
       [11, 2, 4, 5, 0]], dtype=object)

In [34]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
onehotencorder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [0,1,2,3,4])],remainder='passthrough')
X_census_variancia = onehotencorder.fit_transform(X_census_variancia).toarray()
X_census_variancia

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [35]:
# Normalização dos dados

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_census_scaled = scaler.fit_transform(X_census_variancia)
X_census_scaled

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [36]:
# Dividindo a base de dados
from sklearn.model_selection import train_test_split
X_census_treinamento_var, X_census_teste_var, y_census_treinamento_var, y_census_teste_var = train_test_split(X_census_variancia, y_census_variancia, test_size=0.15, random_state=0)
X_census_treinamento_var.shape, X_census_teste_var.shape

((27676, 46), (4885, 46))

In [38]:
# 84.70 sem trabalhar com seleção de atributos
from sklearn.ensemble import RandomForestClassifier
random_forest_var = RandomForestClassifier(criterion = 'entropy', min_samples_leaf =  1, min_samples_split = 5, n_estimators = 100)
random_forest_var.fit(X_census_treinamento_var, y_census_treinamento_var)

RandomForestClassifier(criterion='entropy', min_samples_split=5)

In [39]:
from sklearn.metrics import accuracy_score, classification_report
previsoes = random_forest_var.predict(X_census_teste_var)
accuracy_score(y_census_teste_var, previsoes)

0.8182190378710338

- Piorou o resultado
- em geral esse tipo de estrategia funciona melhor quando trabalhamos com imagens ou com base de dados com MUITOS atributos

# Extra tree

Treinamremos e veremos quais foram os atributos mais importante para essa base

In [40]:
from sklearn.ensemble import ExtraTreesClassifier

In [44]:
base_census = pd.read_csv('/content/drive/MyDrive/Machine Learning e Data Science com Python de A a Z/Bases de dados/census.csv')
X_census = base_census.iloc[:, 0:14].values
y_census = base_census.iloc[:, 14].values
from sklearn.preprocessing import LabelEncoder
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()
# aplicamos um labelEncoder para cada um dos atributos
X_census[:,1] = label_encoder_workclass.fit_transform(X_census[:,1])
X_census[:,3] = label_encoder_education.fit_transform(X_census[:,3])
X_census[:,5] = label_encoder_marital.fit_transform(X_census[:,5])
X_census[:,6] = label_encoder_occupation.fit_transform(X_census[:,6])
X_census[:,7] = label_encoder_relationship.fit_transform(X_census[:,7])
X_census[:,8] = label_encoder_race.fit_transform(X_census[:,8])
X_census[:,9] = label_encoder_sex.fit_transform(X_census[:,9])
X_census[:,13] = label_encoder_country.fit_transform(X_census[:,13])
scaler = MinMaxScaler()
X_census_scaled = scaler.fit_transform(X_census)

In [45]:
X_census_scaled.shape

(32561, 14)

In [46]:
selecao = ExtraTreesClassifier()
selecao.fit(X_census_scaled, y_census)

ExtraTreesClassifier()

In [47]:
importancia = selecao.feature_importances_
importancia

array([0.15640593, 0.0437839 , 0.1649159 , 0.03706024, 0.08845777,
       0.08202948, 0.07432337, 0.08390494, 0.01465294, 0.02778263,
       0.08701971, 0.02721808, 0.0946113 , 0.01783381])

In [50]:
index = []
for i in range(len(importancia)):
  if importancia[i] >= 0.029:
    index.append(i)

In [52]:
colunas[index]

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'capital-gain',
       'hour-per-week'],
      dtype='object')

In [53]:
X_census_extra = X_census[:, index]
X_census_extra

array([[39, 7, 77516, ..., 1, 2174, 40],
       [50, 6, 83311, ..., 0, 0, 13],
       [38, 4, 215646, ..., 1, 0, 40],
       ...,
       [58, 4, 151910, ..., 4, 0, 40],
       [22, 4, 201490, ..., 3, 0, 20],
       [52, 5, 287927, ..., 5, 15024, 40]], dtype=object)

In [54]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
onehotencorder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [1,3,5,6,7])],remainder='passthrough')
X_census_extra = onehotencorder.fit_transform(X_census_extra).toarray()
X_census_extra

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.3000e+01, 2.1740e+03,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.3000e+01, 0.0000e+00,
        1.3000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 9.0000e+00, 0.0000e+00,
        4.0000e+01],
       ...,
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 9.0000e+00, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 9.0000e+00, 0.0000e+00,
        2.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 9.0000e+00, 1.5024e+04,
        4.0000e+01]])

In [55]:
X_census_extra.shape

(32561, 58)

In [56]:
# Dividindo a base de dados
from sklearn.model_selection import train_test_split
X_census_treinamento_extra, X_census_teste_extra, y_census_treinamento_extra, y_census_teste_extra = train_test_split(X_census_extra, y_census, test_size=0.15, random_state=0)
X_census_treinamento_extra.shape, X_census_teste_extra.shape

((27676, 58), (4885, 58))

In [57]:
from sklearn.ensemble import RandomForestClassifier
random_forest_extra = RandomForestClassifier(criterion = 'entropy', min_samples_leaf =  1, min_samples_split = 5, n_estimators = 100)
random_forest_extra.fit(X_census_treinamento_extra, y_census_treinamento_extra)

RandomForestClassifier(criterion='entropy', min_samples_split=5)

In [58]:
# 0.8470
from sklearn.metrics import accuracy_score, classification_report
previsoes = random_forest_extra.predict(X_census_teste_extra)
accuracy_score(y_census_teste_extra, previsoes)

0.844216990788127

Não mudou muita coisa...

Apesar de o accurancy nao ter mudado, a aplicação do onehot encoder resultou num numero bem menor de colunas, logo, o tempo de processamento é bem menor, resultando em um ganho, mesmo nao sendo em relação ao accurancy